In [4]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from io import BytesIO

In [5]:
# URL à télécharger
url = "https://daga123-tv-api.onrender.com/getPrograms"

try:
    # Envoyer une requête GET
    response = requests.get(url)
    
    # Vérifier si la requête a réussi (code 200)
    response.raise_for_status()
    
    # Charger le contenu JSON
    data = response.json()
    
    # Afficher les données
    print(data)
except requests.exceptions.RequestException as e:
    print(f"Erreur lors de la récupération des données : {e}")

{'data': [{'id': 'TF1.fr', 'name': 'TF1', 'icon': 'https://static.teleboy.ch/shared/stations/308/icon320_light.png?v2023_48_0', 'programs': [{'name': "Tirage de l'EuroMillions", 'start': 1764982200, 'end': 1764982500, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/35051CC03C67BBB350BD93AD7806AAA0.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': "Consultez les derniers résultats d'EuroMillions ainsi que les codes gagnants My Million. Découvrez les 5 numéros gagnants et les 2 bonnes étoiles d'EuroMillions mais aussi les codes gagnants My Million des derniers tirages !"}, {'name': 'Programmes de la nuit', 'start': 1764982500, 'end': 1765000200, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/EBE64969228A4E87CCB86326164FE0B7.jpg', 'rating': 'Tout public', 'cat': 'Programme', 'desc': 'A suivre, des rediffusions des émissions de la chaîne, ainsi que des documentaires et autres reportages destinés à divertir les couche-tard comme les lève-tôt.'}, {'name': 'TFou', 'start': 1765000200, 'end': 1765018800, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/6026CDAE7E84331AE03FEFDBF011CD08.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Azuro & la brigade des dragons (ST) / Barbapapa en Famille (ST) / Alice et Lewis (ST) / Dora (ST) / Ruben & cie (ST) / Paw Patrol, la Pat'Patrouille (ST) / Mille Bornes Challenge (ST) / Les chapardeurs (ST) / Miraculous - Les aventures de Ladybug et Chat Noir (AD - ST) / Winx Club : La magie est de retour (ST) / Tu dis, tu stoppes !"}, {'name': 'Téléshopping samedi', 'start': 1765018800, 'end': 1765021500, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/FC968517E17FDB69C2A89C6B56DB5322.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': "Le magazine de la consommation et des conseils d'achat, coaché par Marie-Ange Nardi et Alexandre Devoise."}, {'name': 'Petits plats en équilibre', 'start': 1765021500, 'end': 1765021800, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/379073F402DA5268B6AD131BE7246E81.jpg', 'rating': 'Tout public', 'cat': 'Art de vivre', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Les douze coups de midi', 'start': 1765021800, 'end': 1765025400, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/3004E579827A9BCC65EBD12945E69B15.jpg', 'rating': 'Tout public', 'cat': 'Divertissement', 'desc': "Emission du 6 décembre 2025 - Chaque jour, quatre candidats s'affrontent pour empocher les 30 000 euros de la cagnotte et décrocher l'étoile mystérieuse et ses cadeaux. Seule condition, bien répondre aux questions de culture générale posées par..."}, {'name': 'Petits plats en équilibre', 'start': 1765025400, 'end': 1765025700, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg', 'rating': 'Tout public', 'cat': 'Art de vivre', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Météo', 'start': 1765025700, 'end': 1765026000, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/8F03EA99E2A380FBDFF696EA6BDCEFD2.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': 'Météo du samedi 6 décembre 2025 à 12h48 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du samedi 6 décembre 2025 à 12h48 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'}, {'name': 'JT 13h', 'start': 1765026000, 'end': 1765028400, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/E3BE54678DB73BD513776312912351CD.jpg', 'rating': 'Tout public', 'cat': 'Information', 'desc': '" JT 13h WE " du samedi 6 décembre 2025. Le samedi et dimanche, la rédaction de TF1 propose "LE 13H" un rendez-vous d\'information qui met en exergue l\'actualité régionale, nationale et internationale présenté par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'}, {'name': 'Reportages découverte', 'start': 1765028400, 'end': 1765032600, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/140554741964F405AFC062A1310906DB.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Les 70 agents de l'Office central pour la répression de la grande délinquance financière s'attaquent à une criminalité en apparence invisible, mais qui vole des milliards d'euros chaque année. Une équipe a suivi leur quotidien pendant un an, des enquêtes les plus sensibles aux interpellations les plus périlleuses."}, {'name': 'Reportages découverte', 'start': 1765032600, 'end': 1765037400, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/5D99170DA6DCC8164719E4E12AD1976D.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Ils sont artisans, compagnons, chefs décorateurs de cinéma, décorateurs d'intérieur ou scénographe. On les dit un peu magiciens, car ils inventent de nouveaux lieux, recréent des décors d'époque et restaurent des lieux d'exception. Leurs projets nécessitent des mécanismes ingénieux et beaucoup de créativité. "}, {'name': 'Miss France un jour... Miss France toujours !', 'start': 1765037400, 'end': 1765041600, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/3B612DB6CE8FEC6BFB9E1E672521FD90.jpg', 'rating': 'Tout public', 'cat': 'Documentaire', 'desc': "Le titre de Miss France reste à vie, au sens propre, comme au figuré. Pourtant, lorsqu'elles le décrochent, la plupart de ces femmes ne réalisent pas l'impact qu'il aura sur toute leur existence. Comment se construire avec cette couronne sur la tête ? Six Miss France, couronnées entre 1970 et 2021, ont accepté de témoigner et d'être suivies dans leur quotidien, de Marbella à Los Angeles, sans oublier la Normandie : Amandine Petit (Miss France 2021), Malika Ménard (Miss France 2010), Chloé Mortaud (Miss France 2009), Sophie Thalmann (Miss France 1998), Linda Hardy (Miss France 1992) et Micheline Beaurain (Miss France 1970)."}, {'name': 'Star Academy, la quotidienne', 'start': 1765041600, 'end': 1765043700, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/6537DF939D64320A592A2AACCF9E7FE5.jpg', 'rating': 'Tout public', 'cat': 'Programme', 'desc': 'Retour sur les moments forts de la journée des candidats de "Star Academy" avec un débrief de leurs prestations, des cours et des moments de vie.'}, {'name': "50mn Inside l'actu", 'start': 1765043700, 'end': 1765047600, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/ACAE08220CA31B0CEA910FA289963EC2.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Chaque samedi, Isabelle Ithurburu propose des news, de l'actualité people, des reportages dans l'intimité des stars mais aussi de découvrir des repaires secrets et des destinations de rêve au bout du monde. "}, {'name': '50mn Inside le mag', 'start': 1765047600, 'end': 1765050600, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/775E8761C33FEF8B50F2EE712D7FF044.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Chaque semaine, Isabelle Ithurburu reçoit une personnalité du monde du cinéma, de la chanson, du théâtre. Et s'invite dans l'univers des stars à travers des news, l'actualité des people et des reportages dans l'intimité des célébrités."}, {'name': 'Petits plats en équilibre', 'start': 1765050600, 'end': 1765050900, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg', 'rating': 'Tout public', 'cat': 'Art de vivre', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Météo', 'start': 1765050900, 'end': 1765051200, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/8F03EA99E2A380FBDFF696EA6BDCEFD2.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': 'Prévisions météorologiques en France par le service de TF1.'}, {'name': 'JT 20h', 'start': 1765051200, 'end': 1765053900, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/C81AD70D8108120219B95AD77F3C749F.jpg', 'rating': 'Tout public', 'cat': 'Information', 'desc': '" JT 20h WE " du samedi 6 décembre 2025. Du vendredi au dimanche, la rédaction de TF1 propose "LE 20H" un rendez-vous d\'information exposant avec clarté l\'actualité française et internationale présentée par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'}, {'name': 'Tirage du Loto', 'start': 1765053900, 'end': 1765054200, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/7AE05D882C6EA3D9D33957EADC6F7C74.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': 'Les derniers résultats des Loto. Tous les lundi, mercredi et samedi vers 20h35, Jean-Pierre Foucault, Elsa Fayer, Christophe Beaugrand, Karine Ferri ou Iris Mittenaere présentent les résultats des tirages officiels du Loto avec les cinq numéros gagnants ainsi que le numéro chance des derniers tirages.'}, {'name': 'Petits plats en équilibre', 'start': 1765054200, 'end': 1765054800, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg', 'rating': 'Tout public', 'cat': 'Art de vivre', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Météo', 'start': 1765054800, 'end': 1765055400, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/A5D08C82B41A99323616BCACCB15867D.jpg', 'rating': 'Tout public', 'cat': 'Services', 'desc': 'Météo du samedi 6 décembre 2025 à 20h57 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du samedi 6 décembre 2025 à 20h57 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'}, {'name': 'Élection de miss France', 'start': 1765055400, 'end': 1765063800, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/F1C3E5D9EDC5AACB76FD722343A03469.jpg', 'rating': 'Tout public', 'cat': 'Programme', 'desc': "Traditionnel maître de céans, Jean-Pierre Foucault présente la 30e élection de Miss France. Parmi les trente Miss régionales qui vivent une aventure unique et magnifique, une seule sera sacrée sur la scène du Zénith d'Amiens. Qui succédera à Angélique Angarni-Filopon, Miss France 2025, et sera élue Miss France 2026 ?"}, {'name': 'Élection de miss France', 'start': 1765063800, 'end': 1765068600, 'channel': 'TF1.fr', 'icon': 'https://img.bouygtel.fr/CMS/images/F1C3E5D9EDC5AACB76FD722343A03469.jpg', 'rating': 'Tout public', 'cat': 'Programme', 'desc': 'Avant le dénouement tant attendu, les trente prétendantes au titre se sont envolées pour la Martinique, dite "L\'île aux fleurs". Désormais, place au grand show pour le prime et le couronnement de Miss France 2026. Qui succédera à Angélique Angarni-Filopon, Miss France 2025 ? Réponse à l\'issue de cette seconde partie.'}, {'name': "Miss France 2025 : le parcours d'une miss hors du commun", 'start': 1765068600, 'end': 1765074000, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F600a0c3974b4465190958dc394d1f99a.jpg', 'rating': 'Tout public', 'cat': 'Documentaire', 'desc': "Gros plan sur le parcours d'Angélique Angarni-Filopon, qui est devenue la première Miss Martinique couronnée Miss France en plus d'un siècle de concours."}, {'name': 'Programmes de la nuit', 'start': 1765074000, 'end': 1765086600, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fa371db3166224b3682676d99d7ed5274.jpg', 'rating': 'Tout public', 'cat': 'Autre', 'desc': 'A suivre, des rediffusions des émissions de la chaîne, ainsi que des documentaires et autres reportages destinés à divertir les couche-tard comme les lève-tôt.'}, {'name': 'TFou', 'start': 1765086600, 'end': 1765101900, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Ff30b5095b58844128c95f92484a42caf.jpg', 'rating': 'Tout public', 'cat': 'Jeunesse', 'desc': "Azuro & la brigade des dragons (ST) / Barbapapa en Famille (ST) / Super Wings (ST) / Dora (ST) / Les enquêtes sauvages (ST) / Paw Patrol, la Pat'Patrouille - Mission Pompiers (ST) / Les Shtroumpfs (ST) / Les Chapardeurs (ST) / Miraculous - Les aventures de Ladybug et Chat Noir (AD - ST)"}, {'name': 'Automoto', 'start': 1765101900, 'end': 1765105200, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F86ae06cd44c44eef85858d0d939116b4.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Nouveau logo, nouveau décor, nouvel habillage et nouvelle pilote : Automoto fait peau neuve en cette nouvelle saison. L'émission propose une large diversité de sujets et de reportages : nouvelle rubrique pratique, essais, comparatifs, sports mécaniques, vintage, l'objectif est de réunir et d'expliquer les thématiques automobiles et motos au plus grand nombre."}, {'name': 'Téléfoot', 'start': 1765105200, 'end': 1765108200, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F9f6f40ccdfd04c7596416175ec1a5fa9.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Chaque dimanche, Grégoire Margotton donne rendez-vous pour le meilleur du football mondial en compagnie des consultants qui continuent d'apporter leur expertise pour décrypter l'actualité du football : le champion du monde Bixente Lizarazu, et Rio Mavuba, ancien international français et champion de France avec Lille. A leurs côtés, les journalistes Thomas Mekhiche et Sévérine Parlakou complètent l'équipe."}, {'name': 'Les douze coups de midi', 'start': 1765108200, 'end': 1765111800, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fb651859600b74cf8bea8789b6ebab5a4.jpg', 'rating': 'Tout public', 'cat': 'Divertissement', 'desc': "Emission du 7 décembre 2025 - Chaque jour, quatre candidats s'affrontent pour empocher les 30 000 euros de la cagnotte et décrocher l'étoile mystérieuse et ses cadeaux. Seule condition, bien répondre aux questions de culture générale posées par..."}, {'name': 'Petits plats en équilibre', 'start': 1765111800, 'end': 1765112100, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fcb8fa7eb58904784b095a88cf203581a.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Météo', 'start': 1765112100, 'end': 1765112400, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F06843950a36c4fc7988af95478630854.jpg', 'rating': 'Tout public', 'cat': 'Info-Météo', 'desc': 'Météo du dimanche 7 décembre 2025 à 12h39 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du dimanche 7 décembre 2025 à 12h39 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'}, {'name': 'JT 13h', 'start': 1765112400, 'end': 1765114800, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fbfd67e2d2473459eb1728bb75d44cc0d.jpg', 'rating': 'Tout public', 'cat': 'Info-Météo', 'desc': '" JT 13h WE " du dimanche 7 décembre 2025. Le samedi et dimanche, la rédaction de TF1 propose "LE 13H" un rendez-vous d\'information qui met en exergue l\'actualité régionale, nationale et internationale présenté par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'}, {'name': 'Grands reportages', 'start': 1765114800, 'end': 1765119000, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F650f77a5f0bf45c19af5e5ab373a22c3.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Avec la baisse du pouvoir d'achat, les Français sont devenus les as de la débrouille. Tous les moyens sont bons pour traquer les bons plans, trouver la petite astuce, faire des économies au quotidien. Certains sont même devenus des spécialistes. Pendant plusieurs mois, une équipe a suivi ces rois des économies dans leurs quotidiens parfois étonnants."}, {'name': "Miss France 2025 : le parcours d'une miss hors du commun", 'start': 1765119000, 'end': 1765123500, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F600a0c3974b4465190958dc394d1f99a.jpg', 'rating': 'Tout public', 'cat': 'Documentaire', 'desc': "Gros plan sur le parcours d'Angélique Angarni-Filopon, qui est devenue la première Miss Martinique couronnée Miss France en plus d'un siècle de concours."}, {'name': 'Star Academy, la quotidienne', 'start': 1765123500, 'end': 1765128000, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F43dde678b8324c628b63c099e8eb8962.jpg', 'rating': 'Tout public', 'cat': 'Divertissement', 'desc': 'Retour sur les moments forts de la journée des candidats de "Star Academy" avec un débrief de leurs prestations, des cours et des moments de vie.'}, {'name': 'Sept à huit Life', 'start': 1765128000, 'end': 1765131600, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fdb371a2cd5674e44b498cdaa7806fa21.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': "Des reportages sur la société et l'actualité nationale et internationale, des zooms sur des faits divers ou des gros plans sur des événements marquants du moment invitent à découvrir le monde d'aujourd'hui. Le portrait de la semaine clôt le rendez-vous."}, {'name': 'Sept à huit', 'start': 1765131600, 'end': 1765137000, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F66fd01427e4d4c1694412ffba7da3300.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': 'Une démarche élancée, un port de tête altier, Sigourney Weaver est, à n\'en pas douter, l\'élégance incarnée avec cet air cordial, un brin aristocratique. De retour à l\'écran dans le troisième opus d\'"Avatar", elle est par la même occasion de retour en France. Un pays qu\'elle connaît bien. Elle y séjourne depuis l\'enfance. Au point de très bien en parler la langue. Elle est le portrait de la semaine d\'Audrey Crespo-Mara.'}, {'name': 'Petits plats en équilibre', 'start': 1765137000, 'end': 1765137300, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fcb8fa7eb58904784b095a88cf203581a.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'}, {'name': 'Météo', 'start': 1765137300, 'end': 1765137600, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F06843950a36c4fc7988af95478630854.jpg', 'rating': 'Tout public', 'cat': 'Info-Météo', 'desc': 'Prévisions météorologiques en France par le service de TF1.'}, {'name': 'JT 20h', 'start': 1765137600, 'end': 1765140240, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fef62d38f1f224fbe86d2b5e1ade41c43.jpg', 'rating': 'Tout public', 'cat': 'Info-Météo', 'desc': '" JT 20h WE " du dimanche 7 décembre 2025. Du vendredi au dimanche, la rédaction de TF1 propose "LE 20H" un rendez-vous d\'information exposant avec clarté l\'actualité française et internationale présentée par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'}, {'name': 'TF1, rendez-vous sport', 'start': 1765140240, 'end': 1765140600, 'channel': 'TF1.fr', 'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F6079dc67a9024890a88b3335460010fa.jpg', 'rating': 'Tout public', 'cat': 'Magazine', 'desc': 'Emission du 7 décembre 2025 - Episode 14'}, {'name': 'Le goût du détail', 'start': 1765140600, 'end': 1765141200, 'channel': 'TF1.fr', 'icon': 'ht

In [6]:
# Charger en DataFrame
df = pd.DataFrame(data["data"])

In [7]:
data["data"]

[{'id': 'TF1.fr',
  'name': 'TF1',
  'icon': 'https://static.teleboy.ch/shared/stations/308/icon320_light.png?v2023_48_0',
  'programs': [{'name': "Tirage de l'EuroMillions",
    'start': 1764982200,
    'end': 1764982500,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/35051CC03C67BBB350BD93AD7806AAA0.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': "Consultez les derniers résultats d'EuroMillions ainsi que les codes gagnants My Million. Découvrez les 5 numéros gagnants et les 2 bonnes étoiles d'EuroMillions mais aussi les codes gagnants My Million des derniers tirages !"},
   {'name': 'Programmes de la nuit',
    'start': 1764982500,
    'end': 1765000200,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/EBE64969228A4E87CCB86326164FE0B7.jpg',
    'rating': 'Tout public',
    'cat': 'Programme',
    'desc': 'A suivre, des rediffusions des émissions de la chaîne, ainsi que des documentaires et autres reportages destinés à divertir les couche-tard comme les lève-tôt.'},
   {'name': 'TFou',
    'start': 1765000200,
    'end': 1765018800,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/6026CDAE7E84331AE03FEFDBF011CD08.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Azuro & la brigade des dragons (ST) / Barbapapa en Famille (ST) / Alice et Lewis (ST) / Dora (ST) / Ruben & cie (ST) / Paw Patrol, la Pat'Patrouille (ST) / Mille Bornes Challenge (ST) / Les chapardeurs (ST) / Miraculous - Les aventures de Ladybug et Chat Noir (AD - ST) / Winx Club : La magie est de retour (ST) / Tu dis, tu stoppes !"},
   {'name': 'Téléshopping samedi',
    'start': 1765018800,
    'end': 1765021500,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/FC968517E17FDB69C2A89C6B56DB5322.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': "Le magazine de la consommation et des conseils d'achat, coaché par Marie-Ange Nardi et Alexandre Devoise."},
   {'name': 'Petits plats en équilibre',
    'start': 1765021500,
    'end': 1765021800,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/379073F402DA5268B6AD131BE7246E81.jpg',
    'rating': 'Tout public',
    'cat': 'Art de vivre',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Les douze coups de midi',
    'start': 1765021800,
    'end': 1765025400,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/3004E579827A9BCC65EBD12945E69B15.jpg',
    'rating': 'Tout public',
    'cat': 'Divertissement',
    'desc': "Emission du 6 décembre 2025 - Chaque jour, quatre candidats s'affrontent pour empocher les 30 000 euros de la cagnotte et décrocher l'étoile mystérieuse et ses cadeaux. Seule condition, bien répondre aux questions de culture générale posées par..."},
   {'name': 'Petits plats en équilibre',
    'start': 1765025400,
    'end': 1765025700,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg',
    'rating': 'Tout public',
    'cat': 'Art de vivre',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Météo',
    'start': 1765025700,
    'end': 1765026000,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/8F03EA99E2A380FBDFF696EA6BDCEFD2.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': 'Météo du samedi 6 décembre 2025 à 12h48 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du samedi 6 décembre 2025 à 12h48 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'},
   {'name': 'JT 13h',
    'start': 1765026000,
    'end': 1765028400,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/E3BE54678DB73BD513776312912351CD.jpg',
    'rating': 'Tout public',
    'cat': 'Information',
    'desc': '" JT 13h WE " du samedi 6 décembre 2025. Le samedi et dimanche, la rédaction de TF1 propose "LE 13H" un rendez-vous d\'information qui met en exergue l\'actualité régionale, nationale et internationale présenté par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'},
   {'name': 'Reportages découverte',
    'start': 1765028400,
    'end': 1765032600,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/140554741964F405AFC062A1310906DB.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Les 70 agents de l'Office central pour la répression de la grande délinquance financière s'attaquent à une criminalité en apparence invisible, mais qui vole des milliards d'euros chaque année. Une équipe a suivi leur quotidien pendant un an, des enquêtes les plus sensibles aux interpellations les plus périlleuses."},
   {'name': 'Reportages découverte',
    'start': 1765032600,
    'end': 1765037400,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/5D99170DA6DCC8164719E4E12AD1976D.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Ils sont artisans, compagnons, chefs décorateurs de cinéma, décorateurs d'intérieur ou scénographe. On les dit un peu magiciens, car ils inventent de nouveaux lieux, recréent des décors d'époque et restaurent des lieux d'exception. Leurs projets nécessitent des mécanismes ingénieux et beaucoup de créativité. "},
   {'name': 'Miss France un jour... Miss France toujours !',
    'start': 1765037400,
    'end': 1765041600,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/3B612DB6CE8FEC6BFB9E1E672521FD90.jpg',
    'rating': 'Tout public',
    'cat': 'Documentaire',
    'desc': "Le titre de Miss France reste à vie, au sens propre, comme au figuré. Pourtant, lorsqu'elles le décrochent, la plupart de ces femmes ne réalisent pas l'impact qu'il aura sur toute leur existence. Comment se construire avec cette couronne sur la tête ? Six Miss France, couronnées entre 1970 et 2021, ont accepté de témoigner et d'être suivies dans leur quotidien, de Marbella à Los Angeles, sans oublier la Normandie : Amandine Petit (Miss France 2021), Malika Ménard (Miss France 2010), Chloé Mortaud (Miss France 2009), Sophie Thalmann (Miss France 1998), Linda Hardy (Miss France 1992) et Micheline Beaurain (Miss France 1970)."},
   {'name': 'Star Academy, la quotidienne',
    'start': 1765041600,
    'end': 1765043700,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/6537DF939D64320A592A2AACCF9E7FE5.jpg',
    'rating': 'Tout public',
    'cat': 'Programme',
    'desc': 'Retour sur les moments forts de la journée des candidats de "Star Academy" avec un débrief de leurs prestations, des cours et des moments de vie.'},
   {'name': "50mn Inside l'actu",
    'start': 1765043700,
    'end': 1765047600,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/ACAE08220CA31B0CEA910FA289963EC2.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Chaque samedi, Isabelle Ithurburu propose des news, de l'actualité people, des reportages dans l'intimité des stars mais aussi de découvrir des repaires secrets et des destinations de rêve au bout du monde. "},
   {'name': '50mn Inside le mag',
    'start': 1765047600,
    'end': 1765050600,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/775E8761C33FEF8B50F2EE712D7FF044.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Chaque semaine, Isabelle Ithurburu reçoit une personnalité du monde du cinéma, de la chanson, du théâtre. Et s'invite dans l'univers des stars à travers des news, l'actualité des people et des reportages dans l'intimité des célébrités."},
   {'name': 'Petits plats en équilibre',
    'start': 1765050600,
    'end': 1765050900,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg',
    'rating': 'Tout public',
    'cat': 'Art de vivre',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Météo',
    'start': 1765050900,
    'end': 1765051200,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/8F03EA99E2A380FBDFF696EA6BDCEFD2.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': 'Prévisions météorologiques en France par le service de TF1.'},
   {'name': 'JT 20h',
    'start': 1765051200,
    'end': 1765053900,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/C81AD70D8108120219B95AD77F3C749F.jpg',
    'rating': 'Tout public',
    'cat': 'Information',
    'desc': '" JT 20h WE " du samedi 6 décembre 2025. Du vendredi au dimanche, la rédaction de TF1 propose "LE 20H" un rendez-vous d\'information exposant avec clarté l\'actualité française et internationale présentée par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'},
   {'name': 'Tirage du Loto',
    'start': 1765053900,
    'end': 1765054200,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/7AE05D882C6EA3D9D33957EADC6F7C74.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': 'Les derniers résultats des Loto. Tous les lundi, mercredi et samedi vers 20h35, Jean-Pierre Foucault, Elsa Fayer, Christophe Beaugrand, Karine Ferri ou Iris Mittenaere présentent les résultats des tirages officiels du Loto avec les cinq numéros gagnants ainsi que le numéro chance des derniers tirages.'},
   {'name': 'Petits plats en équilibre',
    'start': 1765054200,
    'end': 1765054800,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/CB757B212CF266819A3DB8045483CF35.jpg',
    'rating': 'Tout public',
    'cat': 'Art de vivre',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Météo',
    'start': 1765054800,
    'end': 1765055400,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/A5D08C82B41A99323616BCACCB15867D.jpg',
    'rating': 'Tout public',
    'cat': 'Services',
    'desc': 'Météo du samedi 6 décembre 2025 à 20h57 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du samedi 6 décembre 2025 à 20h57 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'},
   {'name': 'Élection de miss France',
    'start': 1765055400,
    'end': 1765063800,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/F1C3E5D9EDC5AACB76FD722343A03469.jpg',
    'rating': 'Tout public',
    'cat': 'Programme',
    'desc': "Traditionnel maître de céans, Jean-Pierre Foucault présente la 30e élection de Miss France. Parmi les trente Miss régionales qui vivent une aventure unique et magnifique, une seule sera sacrée sur la scène du Zénith d'Amiens. Qui succédera à Angélique Angarni-Filopon, Miss France 2025, et sera élue Miss France 2026 ?"},
   {'name': 'Élection de miss France',
    'start': 1765063800,
    'end': 1765068600,
    'channel': 'TF1.fr',
    'icon': 'https://img.bouygtel.fr/CMS/images/F1C3E5D9EDC5AACB76FD722343A03469.jpg',
    'rating': 'Tout public',
    'cat': 'Programme',
    'desc': 'Avant le dénouement tant attendu, les trente prétendantes au titre se sont envolées pour la Martinique, dite "L\'île aux fleurs". Désormais, place au grand show pour le prime et le couronnement de Miss France 2026. Qui succédera à Angélique Angarni-Filopon, Miss France 2025 ? Réponse à l\'issue de cette seconde partie.'},
   {'name': "Miss France 2025 : le parcours d'une miss hors du commun",
    'start': 1765068600,
    'end': 1765074000,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F600a0c3974b4465190958dc394d1f99a.jpg',
    'rating': 'Tout public',
    'cat': 'Documentaire',
    'desc': "Gros plan sur le parcours d'Angélique Angarni-Filopon, qui est devenue la première Miss Martinique couronnée Miss France en plus d'un siècle de concours."},
   {'name': 'Programmes de la nuit',
    'start': 1765074000,
    'end': 1765086600,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fa371db3166224b3682676d99d7ed5274.jpg',
    'rating': 'Tout public',
    'cat': 'Autre',
    'desc': 'A suivre, des rediffusions des émissions de la chaîne, ainsi que des documentaires et autres reportages destinés à divertir les couche-tard comme les lève-tôt.'},
   {'name': 'TFou',
    'start': 1765086600,
    'end': 1765101900,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Ff30b5095b58844128c95f92484a42caf.jpg',
    'rating': 'Tout public',
    'cat': 'Jeunesse',
    'desc': "Azuro & la brigade des dragons (ST) / Barbapapa en Famille (ST) / Super Wings (ST) / Dora (ST) / Les enquêtes sauvages (ST) / Paw Patrol, la Pat'Patrouille - Mission Pompiers (ST) / Les Shtroumpfs (ST) / Les Chapardeurs (ST) / Miraculous - Les aventures de Ladybug et Chat Noir (AD - ST)"},
   {'name': 'Automoto',
    'start': 1765101900,
    'end': 1765105200,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F86ae06cd44c44eef85858d0d939116b4.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Nouveau logo, nouveau décor, nouvel habillage et nouvelle pilote : Automoto fait peau neuve en cette nouvelle saison. L'émission propose une large diversité de sujets et de reportages : nouvelle rubrique pratique, essais, comparatifs, sports mécaniques, vintage, l'objectif est de réunir et d'expliquer les thématiques automobiles et motos au plus grand nombre."},
   {'name': 'Téléfoot',
    'start': 1765105200,
    'end': 1765108200,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F9f6f40ccdfd04c7596416175ec1a5fa9.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Chaque dimanche, Grégoire Margotton donne rendez-vous pour le meilleur du football mondial en compagnie des consultants qui continuent d'apporter leur expertise pour décrypter l'actualité du football : le champion du monde Bixente Lizarazu, et Rio Mavuba, ancien international français et champion de France avec Lille. A leurs côtés, les journalistes Thomas Mekhiche et Sévérine Parlakou complètent l'équipe."},
   {'name': 'Les douze coups de midi',
    'start': 1765108200,
    'end': 1765111800,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fb651859600b74cf8bea8789b6ebab5a4.jpg',
    'rating': 'Tout public',
    'cat': 'Divertissement',
    'desc': "Emission du 7 décembre 2025 - Chaque jour, quatre candidats s'affrontent pour empocher les 30 000 euros de la cagnotte et décrocher l'étoile mystérieuse et ses cadeaux. Seule condition, bien répondre aux questions de culture générale posées par..."},
   {'name': 'Petits plats en équilibre',
    'start': 1765111800,
    'end': 1765112100,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fcb8fa7eb58904784b095a88cf203581a.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Météo',
    'start': 1765112100,
    'end': 1765112400,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F06843950a36c4fc7988af95478630854.jpg',
    'rating': 'Tout public',
    'cat': 'Info-Météo',
    'desc': 'Météo du dimanche 7 décembre 2025 à 12h39 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du dimanche 7 décembre 2025 à 12h39 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.'},
   {'name': 'JT 13h',
    'start': 1765112400,
    'end': 1765114800,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fbfd67e2d2473459eb1728bb75d44cc0d.jpg',
    'rating': 'Tout public',
    'cat': 'Info-Météo',
    'desc': '" JT 13h WE " du dimanche 7 décembre 2025. Le samedi et dimanche, la rédaction de TF1 propose "LE 13H" un rendez-vous d\'information qui met en exergue l\'actualité régionale, nationale et internationale présenté par Anne-Claire Coudray ou Audrey Crespo-Mara, sa joker.'},
   {'name': 'Grands reportages',
    'start': 1765114800,
    'end': 1765119000,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F650f77a5f0bf45c19af5e5ab373a22c3.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Avec la baisse du pouvoir d'achat, les Français sont devenus les as de la débrouille. Tous les moyens sont bons pour traquer les bons plans, trouver la petite astuce, faire des économies au quotidien. Certains sont même devenus des spécialistes. Pendant plusieurs mois, une équipe a suivi ces rois des économies dans leurs quotidiens parfois étonnants."},
   {'name': "Miss France 2025 : le parcours d'une miss hors du commun",
    'start': 1765119000,
    'end': 1765123500,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F600a0c3974b4465190958dc394d1f99a.jpg',
    'rating': 'Tout public',
    'cat': 'Documentaire',
    'desc': "Gros plan sur le parcours d'Angélique Angarni-Filopon, qui est devenue la première Miss Martinique couronnée Miss France en plus d'un siècle de concours."},
   {'name': 'Star Academy, la quotidienne',
    'start': 1765123500,
    'end': 1765128000,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F43dde678b8324c628b63c099e8eb8962.jpg',
    'rating': 'Tout public',
    'cat': 'Divertissement',
    'desc': 'Retour sur les moments forts de la journée des candidats de "Star Academy" avec un débrief de leurs prestations, des cours et des moments de vie.'},
   {'name': 'Sept à huit Life',
    'start': 1765128000,
    'end': 1765131600,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fdb371a2cd5674e44b498cdaa7806fa21.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': "Des reportages sur la société et l'actualité nationale et internationale, des zooms sur des faits divers ou des gros plans sur des événements marquants du moment invitent à découvrir le monde d'aujourd'hui. Le portrait de la semaine clôt le rendez-vous."},
   {'name': 'Sept à huit',
    'start': 1765131600,
    'end': 1765137000,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2F66fd01427e4d4c1694412ffba7da3300.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': 'Une démarche élancée, un port de tête altier, Sigourney Weaver est, à n\'en pas douter, l\'élégance incarnée avec cet air cordial, un brin aristocratique. De retour à l\'écran dans le troisième opus d\'"Avatar", elle est par la même occasion de retour en France. Un pays qu\'elle connaît bien. Elle y séjourne depuis l\'enfance. Au point de très bien en parler la langue. Elle est le portrait de la semaine d\'Audrey Crespo-Mara.'},
   {'name': 'Petits plats en équilibre',
    'start': 1765137000,
    'end': 1765137300,
    'channel': 'TF1.fr',
    'icon': 'https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Fcb8fa7eb58904784b095a88cf203581a.jpg',
    'rating': 'Tout public',
    'cat': 'Magazine',
    'desc': 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.'},
   {'name': 'Météo',

In [8]:
df.head()

,id,name,icon,programs
0,TF1.fr,TF1,https://static.teleboy.ch/shared/stations/308/...,"[{'name': 'Tirage de l'EuroMillions', 'start':..."
1,France2.fr,France 2,https://static.teleboy.ch/shared/stations/342/...,"[{'name': 'Le 6h info', 'start': 1765000800, '..."
2,France3.fr,France 3,https://static.teleboy.ch/shared/stations/58/i...,"[{'name': 'Journal Météo Climat', 'start': 176..."
3,CanalPlus.fr,Canal+,https://focus.telerama.fr/500x500/0000/00/01/c...,"[{'name': 'Aimons-nous vivants', 'start': 1764..."
4,France5.fr,France 5,https://static.teleboy.ch/shared/stations/80/i...,"[{'name': 'La p'tite librairie', 'start': 1764..."

In [9]:
df.columns

Index(['id', 'name', 'icon', 'programs'], dtype='object')

In [10]:
def format_programs(programs):
    df_programs = pd.DataFrame(programs)
    df_programs.start = pd.to_datetime(df_programs.start, unit="s")
    df_programs.end = pd.to_datetime(df_programs.end, unit="s")
    return df_programs

In [11]:
df["programs"] = df["programs"].apply(format_programs)

In [12]:
df[df["name"].isin(["TF1", "France 2", "France 3", "Canal+"])]

,id,name,icon,programs
0,TF1.fr,TF1,https://static.teleboy.ch/shared/stations/308/...,name s...
1,France2.fr,France 2,https://static.teleboy.ch/shared/stations/342/...,name ...
2,France3.fr,France 3,https://static.teleboy.ch/shared/stations/58/i...,name start ...
3,CanalPlus.fr,Canal+,https://focus.telerama.fr/500x500/0000/00/01/c...,...

In [13]:
df["programs"][0]

,name,start,end,channel,icon,rating,cat,desc
0,Tirage de l'EuroMillions,2025-12-06 00:50:00,2025-12-06 00:55:00,TF1.fr,https://img.bouygtel.fr/CMS/images/35051CC03C6...,Tout public,Services,Consultez les derniers résultats d'EuroMillion...
1,Programmes de la nuit,2025-12-06 00:55:00,2025-12-06 05:50:00,TF1.fr,https://img.bouygtel.fr/CMS/images/EBE64969228...,Tout public,Programme,"A suivre, des rediffusions des émissions de la..."
2,TFou,2025-12-06 05:50:00,2025-12-06 11:00:00,TF1.fr,https://img.bouygtel.fr/CMS/images/6026CDAE7E8...,Tout public,Magazine,Azuro & la brigade des dragons (ST) / Barbapap...
3,Téléshopping samedi,2025-12-06 11:00:00,2025-12-06 11:45:00,TF1.fr,https://img.bouygtel.fr/CMS/images/FC968517E17...,Tout public,Services,Le magazine de la consommation et des conseils...
4,Petits plats en équilibre,2025-12-06 11:45:00,2025-12-06 11:50:00,TF1.fr,https://img.bouygtel.fr/CMS/images/379073F402D...,Tout public,Art de vivre,Laurent Mariotte donne toutes les astuces pour...
...,...,...,...,...,...,...,...,...
222,"TF1, rendez-vous sport",2025-12-14 20:45:00,2025-12-14 20:50:00,TF1.fr,https://proxymedia.woopic.com/api/v1/images/18...,Tout public,Magazine,Programme court et quotidien qui revient en im...
223,Le goût du détail,2025-12-14 20:50:00,2025-12-14 21:00:00,TF1.fr,https://proxymedia.woopic.com/api/v1/images/18...,Tout public,Magazine,Le goût du détail - Melons. 24
224,Météo,2025-12-14 21:00:00,2025-12-14 21:10:00,TF1.fr,https://proxymedia.woopic.com/api/v1/images/18...,Tout public,Info-Météo,Prévisions météorologiques en France par le se...
225,Red One,2025-12-14 21:10:00,2025-12-14 23:35:00,TF1.fr,https://proxymedia.woopic.com/api/v1/images/18...,-10,Film,"A quelques jours des fêtes de fin d'année, le ..."
226,Dogman,2025-12-14 23:35:00,2025-12-15 01:40:00,TF1.fr,https://proxymedia.woopic.com/api/v1/images/18...,-12,Film,Douglas Munrow a vécu une enfance horrible sou...

In [14]:
df_programs_tf1 = df[df["name"] == "TF1"]["programs"]
df_programs_tf1 = pd.DataFrame(df_programs_tf1.iloc[0])
df_programs_tf1.start = pd.to_datetime(df_programs_tf1.start, unit="s")
df_programs_tf1.end = pd.to_datetime(df_programs_tf1.end, unit="s")

In [15]:
df_programs_tf1["desc"][13]

"Chaque samedi, Isabelle Ithurburu propose des news, de l'actualité people, des reportages dans l'intimité des stars mais aussi de découvrir des repaires secrets et des destinations de rêve au bout du monde. "

In [16]:
from transformers import CamembertTokenizer, CamembertModel
import torch

# Charger le tokenizer et le modèle
tokenizer = CamembertTokenizer.from_pretrained('camembert-base')
model = CamembertModel.from_pretrained('camembert-base')

# Fonction pour générer des embeddings
def generate_embeddings(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)
    outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).detach().numpy()

# Appliquer la fonction à la colonne "desc"
df_programs_tf1['embeddings'] = df_programs_tf1['desc'].apply(generate_embeddings)

In [17]:
# from langchain_ollama import OllamaEmbeddings
# import numpy as np

# # Charger le modèle d'embeddings (sans show_progress)
# embed_model = OllamaEmbeddings(model="llama3:latest")

# # Fonction pour générer des embeddings
# def generate_embeddings(text):
#     try:
#         return np.array(embed_model.embed_query(text))
#     except Exception as e:
#         raise RuntimeError(f"Ollama embedding failed: {e}")

# # Appliquer la fonction à la colonne "desc"
# df_programs_tf1['embeddings_llama'] = df_programs_tf1['desc'].apply(generate_embeddings)

In [95]:
# ...existing code...
import numpy as np

# Use local Gemma-3 12B if available, otherwise fallback to Camembert
MODEL_NAME = "gemma3:12b"
use_ollama = False
embed_model = None

try:
    from langchain_ollama import OllamaEmbeddings
    embed_model = OllamaEmbeddings(model=MODEL_NAME)
    # quick smoke test
    _ = embed_model.embed_query("test")
    use_ollama = True
    print(f"Using local Ollama model: {MODEL_NAME}")
except Exception as e:
    print("Local Ollama (Gemma) unavailable, falling back to Camembert:", e)
    use_ollama = False

if use_ollama:
    def generate_embeddings_gemma(text):
        return np.array(embed_model.embed_query(text))
    df_programs_tf1['embeddings_llama'] = df_programs_tf1['desc'].apply(generate_embeddings_gemma)
else:
    # fallback : Camembert local
    from transformers import CamembertTokenizer, CamembertModel
    import torch
    tokenizer = CamembertTokenizer.from_pretrained('camembert-base')
    camembert_model = CamembertModel.from_pretrained('camembert-base')
    def generate_embeddings_camembert(text):
        inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)
        outputs = camembert_model(**inputs)
        return outputs.last_hidden_state.mean(dim=1).detach().numpy()
    df_programs_tf1['embeddings_llama'] = df_programs_tf1['desc'].apply(generate_embeddings_camembert)
# ...existing code...

Local Ollama (Gemma) unavailable, falling back to Camembert: this model does not support embeddings (status code: 500)

In [18]:
from ollama import Client

client = Client(host='http://localhost:11434')

response = client.generate(
    model='gemma3:12b',
    prompt='Explique la théorie de la relativité en une phrase.'
)

print(response['response'])

La théorie de la relativité, formulée par Einstein, décrit comment l'espace et le temps sont liés pour tous les observateurs, et comment la vitesse de la lumière est constante, conduisant à des effets contre-intuitifs comme la dilatation du temps et la contraction des longueurs à des vitesses proches de celle de la lumière.

In [19]:
# for chunk in client.generate(
#     model='gemma3:12b',
#     prompt='Résume Le Petit Prince.',
#     stream=True
# ):
#     print(chunk['response'], end="")

In [20]:
# ...existing code...
import numpy as np

# Use local Gemma-3 12B if available, otherwise fallback to Camembert
MODEL_NAME = "gemma3:12b"
use_ollama = False
embed_model = None

try:
    from ollama import Client
    client = Client(host='http://localhost:11434')

    # --- Test rapide pour voir si le modèle est dispo ---
    test = client.embeddings(model=MODEL_NAME, prompt="test")
    embed_dim = len(test["embedding"])
    print(f"Using local Ollama model: {MODEL_NAME} (embedding size={embed_dim})")

    use_ollama = True

except Exception as e:
    print("Local Ollama (Gemma) unavailable, falling back to Camembert:", e)
    use_ollama = False


# === Embeddings with Ollama (Gemma) ===
if use_ollama:

    def generate_embeddings_gemma(text):
        result = client.embeddings(model=MODEL_NAME, prompt=text)
        return np.array(result["embedding"])

    df_programs_tf1['embeddings_llama'] = df_programs_tf1['desc'].apply(generate_embeddings_gemma)

# === Fallback Camembert ===
else:
    from transformers import CamembertTokenizer, CamembertModel
    import torch

    tokenizer = CamembertTokenizer.from_pretrained('camembert-base')
    camembert_model = CamembertModel.from_pretrained('camembert-base')

    def generate_embeddings_camembert(text):
        inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)
        outputs = camembert_model(**inputs)
        return outputs.last_hidden_state.mean(dim=1).detach().numpy()

    df_programs_tf1['embeddings_llama'] = df_programs_tf1['desc'].apply(generate_embeddings_camembert)

# ...existing code...

Local Ollama (Gemma) unavailable, falling back to Camembert: this model does not support embeddings (status code: 500)

In [21]:
df_programs_tf1.iloc[13]

name                                               50mn Inside l'actu
start                                             2025-12-06 17:55:00
end                                               2025-12-06 19:00:00
channel                                                        TF1.fr
icon                https://img.bouygtel.fr/CMS/images/ACAE08220CA...
rating                                                    Tout public
cat                                                          Magazine
desc                Chaque samedi, Isabelle Ithurburu propose des ...
embeddings          [[0.080596134, 0.031361695, 0.06708018, 0.1375...
embeddings_llama    [[0.080596134, 0.031361695, 0.06708018, 0.1375...
Name: 13, dtype: object

In [22]:
df_programs_tf1.iloc[13]["embeddings"].shape

(1, 768)

In [23]:
df_programs_tf1.iloc[13]["embeddings_llama"].shape

(1, 768)

In [24]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Embedding cible
target_embedding = df_programs_tf1["embeddings"][13].reshape(1, -1)

# Reshape embeddings to 2D arrays
embeddings_2d = np.array(df_programs_tf1["embeddings"].tolist()).reshape(len(df_programs_tf1), -1)

# Calculer les similarités cosinus
similarities = cosine_similarity(target_embedding, embeddings_2d)[0]

# Trouver les indices des n lignes les plus proches
n = 5  # Remplacez par le nombre de lignes souhaité
closest_indices = np.argsort(similarities)[-n:][::-1]

# Récupérer les n lignes les plus proches
closest_rows = df_programs_tf1.iloc[closest_indices]

print(closest_rows["name"])
print(closest_rows["desc"])

13                      50mn Inside l'actu
14                      50mn Inside le mag
196                     50mn Inside le mag
195                     50mn Inside le mag
205    Star Academy, retour au château S13
Name: name, dtype: object
13     Chaque samedi, Isabelle Ithurburu propose des ...
14     Chaque semaine, Isabelle Ithurburu reçoit une ...
196    50' Inside, c'est toute l'actualité des stars ...
195    50' Inside, c'est toute l'actualité des stars ...
205    A l'issue du prime, les académiciens qui conti...
Name: desc, dtype: object

In [25]:
# Embeddings llama
# Embedding cible
target_embedding_llama = df_programs_tf1["embeddings_llama"][13].reshape(1, -1)

# Reshape embeddings to 2D arrays
embeddings_2d_llama = np.array(df_programs_tf1["embeddings_llama"].tolist()).reshape(len(df_programs_tf1), -1)

# Calculer les similarités cosinus
similarities_llama = cosine_similarity(target_embedding_llama, embeddings_2d_llama)[0]

# Trouver les indices des n lignes les plus proches
n = 5  # Remplacez par le nombre de lignes souhaité
closest_indices_llama = np.argsort(similarities_llama)[-n:][::-1]

# Récupérer les n lignes les plus proches
closest_rows_llama = df_programs_tf1.iloc[closest_indices_llama]

print(closest_rows_llama["name"])
print(closest_rows_llama["desc"])

13                      50mn Inside l'actu
14                      50mn Inside le mag
196                     50mn Inside le mag
195                     50mn Inside le mag
205    Star Academy, retour au château S13
Name: name, dtype: object
13     Chaque samedi, Isabelle Ithurburu propose des ...
14     Chaque semaine, Isabelle Ithurburu reçoit une ...
196    50' Inside, c'est toute l'actualité des stars ...
195    50' Inside, c'est toute l'actualité des stars ...
205    A l'issue du prime, les académiciens qui conti...
Name: desc, dtype: object

In [26]:
# df_programs_tf1.to_excel("programs_tf1.xlsx")

In [27]:
# df_programs_tf1_note.to_pickle('df_programs_tf1_note.pkl')

In [28]:
df_programs_tf1_note = pd.read_pickle('df_programs_tf1_note.pkl')

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Préparer les données
df = df_programs_tf1_note.copy()

# Encoder la colonne "cat"
label_encoder_cat = LabelEncoder()
label_encoder_rating = LabelEncoder()
df['cat_encoded'] = label_encoder_cat.fit_transform(df['cat'])
df['rating_encoded'] = label_encoder_rating.fit_transform(df['rating'])

# Séparer les caractéristiques (features) et la cible (target)
X = np.hstack((df[['rating_encoded', 'cat_encoded']].values, np.vstack(df['embeddings'])))
y = df['note'].values

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
# Normaliser les caractéristiques
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
# Convertir les données en tenseurs PyTorch
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Créer des DataLoader pour l'entraînement et le test
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Construire le modèle
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.dropout1 = nn.Dropout(0.2)
        self.fc2 = nn.Linear(128, 64)
        self.dropout2 = nn.Dropout(0.2)
        self.fc3 = nn.Linear(64, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.dropout1(x)
        x = torch.relu(self.fc2(x))
        x = self.dropout2(x)
        x = self.fc3(x)
        return x

input_dim = X_train.shape[1]
model = NeuralNetwork(input_dim)

# Définir la fonction de perte et l'optimiseur
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Entraîner le modèle
num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
    
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
    # torch.save(model.state_dict(), "trained_model.pth")
    
# Évaluer le modèle
model.eval()
with torch.no_grad():
    y_pred = model(X_test_tensor)
    test_loss = criterion(y_pred, y_test_tensor)
    print(f'Test Loss: {test_loss.item():.4f}')

# Prédire les notes
y_pred = y_pred.numpy()

Epoch [1/50], Loss: 24.7042
Epoch [2/50], Loss: 2.3904
Epoch [3/50], Loss: 0.9054
Epoch [4/50], Loss: 8.2695
Epoch [5/50], Loss: 5.3076
Epoch [6/50], Loss: 0.2928
Epoch [7/50], Loss: 0.0770
Epoch [8/50], Loss: 2.4032
Epoch [9/50], Loss: 2.1264
Epoch [10/50], Loss: 0.3551
Epoch [11/50], Loss: 0.7008
Epoch [12/50], Loss: 1.8010
Epoch [13/50], Loss: 0.2784
Epoch [14/50], Loss: 2.0018
Epoch [15/50], Loss: 1.0326
Epoch [16/50], Loss: 0.7755
Epoch [17/50], Loss: 9.9304
Epoch [18/50], Loss: 0.9681
Epoch [19/50], Loss: 0.3266
Epoch [20/50], Loss: 1.2530
Epoch [21/50], Loss: 0.4511
Epoch [22/50], Loss: 0.2775
Epoch [23/50], Loss: 0.5840
Epoch [24/50], Loss: 2.1351
Epoch [25/50], Loss: 0.3388
Epoch [26/50], Loss: 0.9687
Epoch [27/50], Loss: 0.0500
Epoch [28/50], Loss: 0.0845
Epoch [29/50], Loss: 0.8500
Epoch [30/50], Loss: 5.8045
Epoch [31/50], Loss: 2.6075
Epoch [32/50], Loss: 1.0144
Epoch [33/50], Loss: 0.6415
Epoch [34/50], Loss: 1.1397
Epoch [35/50], Loss: 0.3460
Epoch [36/50], Loss: 0.1130
Epoch [37/50], Loss: 0.3803
Epoch [38/50], Loss: 0.2480
Epoch [39/50], Loss: 0.0888
Epoch [40/50], Loss: 0.2134
Epoch [41/50], Loss: 0.1652
Epoch [42/50], Loss: 3.8152
Epoch [43/50], Loss: 0.5067
Epoch [44/50], Loss: 1.6800
Epoch [45/50], Loss: 8.9674
Epoch [46/50], Loss: 0.9524
Epoch [47/50], Loss: 0.3391
Epoch [48/50], Loss: 1.2703
Epoch [49/50], Loss: 0.1970
Epoch [50/50], Loss: 2.5440
Test Loss: 2.6273

## Prediction

In [32]:
# Préparer les données
df_new = df_programs_tf1.copy()

# Encoder la colonne "cat"
df_new['cat_encoded'] = label_encoder_cat.fit_transform(df_new['cat'])
df_new['rating_encoded'] = label_encoder_rating.fit_transform(df_new['rating'])

# Séparer les caractéristiques (features) et la cible (target)
X_new = np.hstack((df_new[['rating_encoded', 'cat_encoded']].values, np.vstack(df_new['embeddings'])))

In [33]:
X_new_tensor = torch.tensor(X_new, dtype=torch.float32)

In [34]:
X_new_tensor.shape

torch.Size([227, 770])

In [35]:
model.eval()
with torch.no_grad():
    y_pred_new = model(X_new_tensor)
    y_pred_new = y_pred_new.numpy()

In [36]:
y_pred_new

array([[0.08469263],
       [0.07729301],
       [0.07548135],
       [0.06605479],
       [0.3394745 ],
       [0.12942608],
       [0.3394745 ],
       [0.1128102 ],
       [0.13906266],
       [0.15794884],
       [0.17537807],
       [0.28079116],
       [0.07820926],
       [0.21908495],
       [0.14618838],
       [0.3394745 ],
       [0.05849409],
       [0.14137535],
       [0.10859676],
       [0.3394745 ],
       [0.1171869 ],
       [0.15297666],
       [0.16190803],
       [0.20028384],
       [0.16283725],
       [0.05237306],
       [0.11252982],
       [0.1672427 ],
       [0.13126434],
       [0.10384096],
       [0.09928211],
       [0.14895003],
       [0.1388525 ],
       [0.20028384],
       [0.13456547],
       [0.18295942],
       [0.18704261],
       [0.10384096],
       [0.02861977],
       [0.15295   ],
       [0.0376299 ],
       [0.04363068],
       [0.10122376],
       [0.19285533],
       [0.23256992],
       [0.16283725],
       [0.04625084],
       [0.08939648],
       [0.05215183],
       [0.17915   ],
       [0.10384096],
       [0.26075798],
       [0.07791258],
       [0.10384096],
       [0.13443483],
       [0.10384096],
       [0.02861977],
       [0.14696981],
       [0.26077005],
       [0.2607712 ],
       [0.13456547],
       [0.15320453],
       [0.08882035],
       [0.02861977],
       [0.16920586],
       [0.19959284],
       [0.02861977],
       [0.29379845],
       [0.1443624 ],
       [0.17825703],
       [0.11233852],
       [0.1631522 ],
       [0.17099608],
       [0.13691933],
       [0.15807687],
       [0.06233608],
       [0.11749321],
       [0.05804253],
       [0.09671188],
       [0.10848445],
       [0.09656196],
       [0.09044433],
       [0.10848445],
       [0.12348737],
       [0.10848445],
       [0.05621696],
       [0.13952275],
       [0.16898005],
       [0.20862956],
       [0.14554957],
       [0.1311491 ],
       [0.13293873],
       [0.05621696],
       [0.15319908],
       [0.04707756],
       [0.05621696],
       [0.30475214],
       [0.15992348],
       [0.28459272],
       [0.2700433 ],
       [0.14191283],
       [0.16283725],
       [0.04625084],
       [0.08939648],
       [0.05215183],
       [0.17915   ],
       [0.10384096],
       [0.26075798],
       [0.07791258],
       [0.10384096],
       [0.13443483],
       [0.10384096],
       [0.02861977],
       [0.10605922],
       [0.16813578],
       [0.21967474],
       [0.13456547],
       [0.12878604],
       [0.12676172],
       [0.02861977],
       [0.16920586],
       [0.19959284],
       [0.02861977],
       [0.29379845],
       [0.14675377],
       [0.15209201],
       [0.13387333],
       [0.13428475],
       [0.17021267],
       [0.17867328],
       [0.16283725],
       [0.04625084],
       [0.08939648],
       [0.05215183],
       [0.17915   ],
       [0.10384096],
       [0.26075798],
       [0.07791258],
       [0.10384096],
       [0.13443483],
       [0.10384096],
       [0.02861977],
       [0.12202539],
       [0.27512115],
       [0.2343286 ],
       [0.13456547],
       [0.12571213],
       [0.11157254],
       [0.02861977],
       [0.16920586],
       [0.02861977],
       [0.29379845],
       [0.14908211],
       [0.13359901],
       [0.11233852],
       [0.15768147],
       [0.1704944 ],
       [0.16283725],
       [0.04625084],
       [0.08939648],
       [0.05215183],
       [0.17915   ],
       [0.10384096],
       [0.26075798],
       [0.07791258],
       [0.10384096],
       [0.13443483],
       [0.10384096],
       [0.02861977],
       [0.14557464],
       [0.14151523],
       [0.2302305 ],
       [0.13456547],
       [0.13992283],
       [0.09807827],
       [0.02861977],
       [0.16920586],
       [0.12967578],
       [0.02861977],
       [0.29379845],
       [0.28291973],
       [0.2578494 ],
       [0.4022651 ],
       [0.08702854],
       [0.04926894],
       [0.14263254],
       [0.10848445],
       [0.09656196],
       [0.10848445],
       [0.05621696],
       [0.12348737],
       [0.14059566],
       [0.24907175],
       [0.20291822],
       [0.14554957],
       [0.23552519],
       [0.23552519],
       [0.10848445],
       [0.05621696],
       [0.15319908],
       [0.09110595],
       [0.10848445],
       [0.05621696],
       [0.18182841],
       [0.18641718],
       [0.16919158],
       [0.16283725],
       [0.03698189],
       [0.11252982],
       [0.1672427 ],
       [0.26075798],
       [0.10384096],
       [0.02861977],
       [0.13443483],
       [0.19553988],
       [0.15396495],
       [0.13456547],
       [0.18295942],
       [0.18295942],
       [0.10384096],
       [0.02861977],
       [0.16920586],
       [0.09392874],
       [0.04363068],
       [0.02861977],
       [0.2712934 ],
       [0.19482203]], dtype=float32)

In [37]:
df_new['note_pred'] = y_pred_new

In [38]:
df_new.columns

Index(['name', 'start', 'end', 'channel', 'icon', 'rating', 'cat', 'desc',
       'embeddings', 'embeddings_llama', 'cat_encoded', 'rating_encoded',
       'note_pred'],
      dtype='object')

In [39]:
df_new["cat"].unique()

array(['Services', 'Programme', 'Magazine', 'Art de vivre',
       'Divertissement', 'Information', 'Documentaire', 'Autre',
       'Jeunesse', 'Info-Météo', 'Film', 'Série', 'Série Policière',
       "Magazine d'information", 'Jeu', 'Mag Société', 'Infos', 'Météo',
       'Série Dramatique', 'Télé-Réalité', 'Fantastique'], dtype=object)

In [40]:
df_new.query('cat == "Film"').sort_values('note_pred', ascending=False)[["name", "note_pred", "desc"]]

,name,note_pred,desc
143,Un Noël étoilé,0.275121,"Kat, une astrophysicienne, voit les séquelles ..."
225,Red One,0.271293,"A quelques jours des fêtes de fin d'année, le ..."
59,L'héritière de Noël,0.260771,"Jessica, jeune femme à la tête d'une fortune h..."
58,Un rendez-vous parfait pour Noël,0.260770,Annie et Dave se rencontrent dans un grand hôt...
144,Noël au palace,0.234329,Jessica est historienne. Elle se voit confier ...
44,Death Wish,0.232570,"Paul Kersey, chirurgien urgentiste respecté, m..."
171,Coup de foudre en cadeau de Noël,0.230230,Toujours décidée à sauver sa société de lifest...
115,Noël tout feu tout flamme,0.219675,"Olivia, professeur de ballet, confie à son élè..."
88,Les 5 trésors de Noël,0.208630,"Pour rendre hommage à sa grand-mère décédée, u..."
226,Dogman,0.194822,Douglas Munrow a vécu une enfance horrible sou...
43,Noël joyeux,0.192855,Après avoir appris que ses enfants ne seront p...
87,Un manoir en cadeau,0.168980,Partie participer à un concours de Noël dans s...
114,L'étincelle de Noël,0.168136,Dani est lieutenante chez les pompiers dans la...
170,Trois Noëls à la maison,0.141515,"A Cherry Lane, trois couples, qui vivent à tro..."

In [41]:
best_notes = df_new[['name', 'note_pred', 'desc']].sort_values(by='note_pred', ascending=False).head(20)
best_notes

,name,note_pred,desc
182,"Vendredi, tout est permis avec Arthur",0.402265,"Comme toujours, le ""Vendredi, tout est permis ..."
6,Petits plats en équilibre,0.339474,Laurent Mariotte donne toutes les astuces pour...
15,Petits plats en équilibre,0.339474,Laurent Mariotte donne toutes les astuces pour...
19,Petits plats en équilibre,0.339474,Laurent Mariotte donne toutes les astuces pour...
4,Petits plats en équilibre,0.339474,Laurent Mariotte donne toutes les astuces pour...
96,C'est Canteloup,0.304752,"Détournements d'images d'actualité, parodies, ..."
67,C'est Canteloup,0.293798,"Détournements d'images d'actualité, parodies, ..."
151,C'est Canteloup,0.293798,"Détournements d'images d'actualité, parodies, ..."
179,C'est Canteloup,0.293798,"Détournements d'images d'actualité, parodies, ..."
123,C'est Canteloup,0.293798,"Détournements d'images d'actualité, parodies, ..."
98,Harry Potter : Les Sorciers de la pâtisserie S1,0.284593,"En demi-finale, les équipes restantes doivent ..."
180,Bataille navale,0.282920,Arthur donne rendez-vous pour faire découvrir ...
11,Miss France un jour... Miss France toujours !,0.280791,"Le titre de Miss France reste à vie, au sens p..."
143,Un Noël étoilé,0.275121,"Kat, une astrophysicienne, voit les séquelles ..."
225,Red One,0.271293,"A quelques jours des fêtes de fin d'année, le ..."
99,Harry Potter : Les Sorciers de la pâtisserie,0.270043,"Pour la finale de ce concours plein de magie, ..."
59,L'héritière de Noël,0.260771,"Jessica, jeune femme à la tête d'une fortune h..."
58,Un rendez-vous parfait pour Noël,0.260770,Annie et Dave se rencontrent dans un grand hôt...
51,Les douze coups de midi,0.260758,"Chaque jour, des candidats tentent de répondre..."
210,Les douze coups de midi,0.260758,"Chaque jour, des candidats tentent de répondre..."

In [42]:
best_notes.iloc[0]["desc"]

'Comme toujours, le "Vendredi, tout est permis avec Arthur". Et ce ne sont pas les célèbres invités du traditionnel maître de céans qui diront le contraire, eux que l\'animateur fait danser, chanter, mimer, improviser et bien plus encore. Mais puisque le show l\'exige, tous se prêtent de bonne grâce aux facéties du vendredi soir, relevant des défis parfois fous, comme celui du "Décor penché". Les frasques des invités, les fous rires et les dérapages plus ou moins contrôlés sont la matière première de ce rendez-vous qui permet de conclure la semaine en beauté et d\'accueillir le week-end dans les meilleures dispositions.'

## OLLama

In [43]:
# ...existing code...

from ollama import Client
import sys

MODEL_NAME = "gemma3:12b"

# == 1) Try to connect to local Ollama ==
use_ollama = True
try:
    client = Client(host='http://localhost:11434')
    # smoke test
    _ = client.generate(model=MODEL_NAME, prompt="ping")
except Exception as e:
    print("❌ Ollama not reachable:", e)
    use_ollama = False


# == 2) Build the prompt safely ==
try:
    prompt_text = (
        "j'aime les films d'action et les polars, "
        f"est-ce que je vais aimer ce programme ? : {best_notes.iloc[0]['desc']}"
    )
except Exception:
    prompt_text = "j'aime les films d'action et les polars, est-ce que je vais aimer ce programme ?"


# == 3) If Ollama works: run a chat completion ==
if use_ollama:
    try:
        resp = client.chat(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt_text}]
        )
        content = resp["message"]["content"]
        print(content)

    except Exception as e:
        print("❌ Ollama chat failed:", e)
        use_ollama = False


# == 4) Clean Fallback ==
if not use_ollama:
    print("\n⚠️ FALLBACK — program description:\n")
    if len(best_notes):
        print(best_notes.iloc[0]["desc"])
    else:
        print("(no notes found)")

    print("\nTo diagnose your Ollama installation, run:")
    print("  ollama --version")
    print("  ollama list")
    print("  curl http://localhost:11434/api/tags")

Non, à moins que vous ayez un humour très particulier et que vous ne soyez prêt à abandonner vos attentes concernant l'action et le suspense.

Ce programme, "Vendredi, tout est permis avec Arthur", est un divertissement télévisé de variété. Il s'agit d'un jeu d'improvisation et de défis humoristiques entre Arthur et ses invités.

**Ce n'est pas un film d'action ni un polar.** Il n'y a pas d'enquête, de poursuite, de combats, ou de tension dramatique. C'est purement axé sur le rire et l'humour.

**Pourquoi vous pourriez ne pas l'aimer si vous aimez l'action et les polars :**

*   **Absence d'action et de suspense :** C'est un divertissement léger et sans enjeu.
*   **Humour potentiellement différent :** L'humour de ce type de programme peut être subjectif et ne correspond pas forcément aux goûts de ceux qui préfèrent l'action et le suspense.
*   **Inattendu :** La nature imprévisible des improvisations pourrait être déroutante si vous recherchez une narration structurée.

En résumé, si vous êtes à la recherche d'adrénaline et de suspense, ce programme ne vous conviendra probablement pas. Mais si vous cherchez à vous détendre et à rire, vous pourriez essayer.